# https://taskfile.dev

version: "3"

vars:
  PLATFORMS:
    - aarch64-apple-darwin
    - x86_64-unknown-linux-gnu
    - x86_64-pc-windows-msvc
  PROJECT_VERSION:
    sh: cargo read-manifest | jq -r '.version'

tasks:
  # Build
  build-aarch64-apple-darwin:
    cmds:
      - cargo build --release --target aarch64-apple-darwin

  build-x86_64-unknown-linux-gnu:
    cmds:
      - cargo build --release --target x86_64-unknown-linux-gnu

  build-x86_64-pc-windows-msvc:
    cmds:
      - cargo xwin build --release --target x86_64-pc-windows-msvc

  build-all:
    desc: Builds for all supported platforms one after the other.
    cmds:
      - for: { var: PLATFORMS, as: PLATFORM }
        task: build-{{.PLATFORM}}

  # Bundle
  bundle-aarch64-apple-darwin:
    desc: Creates a .app dir for MacOS installation.
    deps:
      - build-aarch64-apple-darwin
    cmds:
      - cargo bundle --release --target aarch64-apple-darwin

  bundle-x86_64-unknown-linux-gnu:
    desc: Creates a .deb package for debian installation.
    deps:
      - build-x86_64-unknown-linux-gnu
    cmds:
      - cargo bundle --release --target x86_64-unknown-linux-gnu

  bundle-x86_64-pc-windows-msvc:
    desc: Creates a .msi installer for windows installation.
    deps:
      - build-x86_64-pc-windows-msvc
    cmds:
      - echo "Windows bundling is not supported yet."
      # - cargo bundle --release --target x86_64-pc-windows-msvc --format msi

  bundle-all:
    desc: Runs all individual bundlers, creating packages for the supported platforms.
    cmds:
      - for: { var: PLATFORMS, as: PLATFORM }
        task: bundle-{{.PLATFORM}}

  # package
  package-release:
    desc: Moves all the binaries to a single folder for release on github.
    deps:
      - bundle-all
    vars:
      OUTPUT_DIR: ./target/github-release
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}
      - for: { var: PLATFORMS, as: PLATFORM }
        cmd: |
          if [[ "{{.PLATFORM}}" == "x86_64-pc-windows-msvc" ]]; then
            mv ./target/{{.PLATFORM}}/release/repo-save-manager.exe {{.OUTPUT_DIR}}/repo-save-manager_{{.PROJECT_VERSION}}-{{.PLATFORM}}.exe
          else
            mv ./target/{{.PLATFORM}}/release/repo-save-manager {{.OUTPUT_DIR}}/repo-save-manager_{{.PROJECT_VERSION}}-{{.PLATFORM}}
          fi
      - cmd: mv './target/x86_64-unknown-linux-gnu/release/bundle/deb/repo-save-manager_{{.PROJECT_VERSION}}_amd64.deb' {{.OUTPUT_DIR}}/repo-save-manager_{{.PROJECT_VERSION}}_x86_64.deb
      - cmd: mv './target/aarch64-apple-darwin/release/bundle/osx/R.E.P.O. Save Manager.app' {{.OUTPUT_DIR}}/
